language: cpp
compiler: gcc
script:
  - mkdir build
  - cd build
  - wget https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh && chmod a+x cmake-3.6.3-Linux-x86_64.sh && ./cmake-3.6.3-Linux-x86_64.sh --skip-license
  - cmake .. && make

