language: cpp
compiler: gcc
dist: trusty
sudo: required
install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install libavutil-dev libavformat-dev libavcodec-dev libswscale-dev
script:
  - qmake --version
  - qmake-qt5 --version
  - mkdir build_3rd
  - cd build_3rd
  - cmake ../3rd/ && make && sudo make install
  - cd ..
  - mkdir build
  - cd build
  - cmake .. && make

